Add tags variable for supported resources
plus3it/terraform-aws-org-new-account-iam-role pull request #123
Opened 2021-07-13 17:01 UTC by kumoy

2021-07-13 18:36 UTC, lorengordon commented
Just closing and re-opening to trigger travis-ci...

2021-07-13 19:04 UTC, lorengordon requested changes
@kumoy Please run `terraform fmt -recursive`, and generate the readme to include the new variable.

2021-07-13 19:04 UTC, lorengordon commented on main.tf
> +  tags          = var.tag
```suggestion
  tags          = var.tags
```

2021-07-14 12:54 UTC, kumoy commented
@lorengordon made the requested changes!

2021-07-14 13:37 UTC, lorengordon approved these changes

2021-07-14 14:33 UTC, merged